---
abstract: ~
author:
  - 'Tokuhiro Matsuno <tokuhirom ah! gmail.com>'
build_requires:
  Devel::CheckLib: 0
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-LibRaw
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  perl: 5.8.5
resources:
  repository: git://github.com/tokuhirom/image-libraw.git
version: 0.01
