---
abstract: ~
author:
  - 'Tokuhiro Matsuno <tokuhirom ah! gmail.com>'
build_requires:
  Devel::CheckLib: 0
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  Test::More: 0
  Test::Requires: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-LibRaw
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  XSLoader: 0.02
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tokuhirom/image-libraw.git
version: 0.03
